name: Deploy Vite Frontend to GitHub Pages

on:
  push:
    branches:
      - master # Cambia esto si tu rama principal se llama "master"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json  # Cache de dependencias

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Create .env file
        run: echo "VITE_BACKEND_HOST=${{ secrets.VITE_BACKEND_HOST }}" > .env.production
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist  # Carpeta generada por Vite

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
